Repository pulumi/pulumi-linode, pull requests merged in 2019-06, with the labels that each got.

#8 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#9 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/domain.ts
  sdk/nodejs/domainRecord.ts
  sdk/nodejs/image.ts
  sdk/nodejs/instance.ts
  sdk/nodejs/nodeBalancer.ts
  sdk/nodejs/nodeBalancerConfig.ts
  sdk/nodejs/nodeBalancerNode.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/rdns.ts
  sdk/nodejs/sshKey.ts
  sdk/nodejs/stackScript.ts
  sdk/nodejs/token.ts
  sdk/nodejs/volume.ts
Labels: area/providers

#11 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#12 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
